---
abstract: 'Force an action to be (in)secure only.'
author:
  - 'Simon Elliott <cpan@papercreatures.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-ActionRole-RequireSSL
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Runtime: 5.8
  Catalyst::Test: 0
  Moose::Role: 0
  namespace::autoclean: 0
  parent: 0
resources:
  repository: git://github.com/papercreatures/Catalyst-ActionRole-RequireSSL.git
version: 0.07
